on:
  pull_request:
    types: [opened, reopened, edited]
    
name : pullrequesttrigger

run-name : ubuntu:latest

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod a+x date.sh
          ./date.sh >> report.md
