on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'main'
  push:
    branches:
      - 'dev/**'
    
name : pullrequesttrigger

run-name : ubuntu:latest

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          chmod a+x date.sh
          ./date.sh >> report.md
          cat report.md
          
      - id: pr
        run: |
          issue=$(gh pr list --search "${{ github.sha }}" --state open --json number --jq ".[0].number")
          echo "issue=$issue" >>$GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: mshick/add-pr-comment@v2
        with:
          issue: ${{ steps.pr.outputs.issue }}
          message-path: 
            report.md
